version: '3.9'

networks:
  nvst-network:
    name: nvst-network
    driver: bridge

services:
  nvst-nestjs-api:
    build: .
    container_name: nvst-nestjs-api
    image: nvst-nestjs-api:latest
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 3100:3000
    volumes:
      - ${PWD}:/app
    networks:
      - nvst-network
    depends_on:
      - postgres
    
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=vXMI0QI8bXq2
      - TZ=America/Sao_Paulo
    ports:
      - 5432:5432
    networks:
      - nvst-network